### ISSUE TITLE
Exception when running shell script

### ISSUE THREAD

**Issue by si-hb** [dkd/plantuml#15]
Here is my script file and output when run:

```
root@si:/usr/bin/plantuml# cat plantuml.sh
#!/bin/bash
/usr/bin/java -Djava.io.tmpdir=/var/tmp -Djava.awt.headless=true -jar /usr/bin/plantuml/plantuml.jar ${@}

root@si:/usr/bin/plantuml# ./plantuml.sh
Exception in thread "main" java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:535)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:218)
        at net.sourceforge.plantuml.swing.MainWindow2.<init>(MainWindow2.java:159)
        at net.sourceforge.plantuml.Run.main(Run.java:134)
root@si:/usr/bin/plantuml#
root@si:/usr/bin/plantuml# java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)
root@si:/usr/bin/plantuml# 
```
### What Redmine shows we try to configure the plugin:

![404](https://user-images.githubusercontent.com/1800110/32355682-906c414e-c006-11e7-9756-f5000c69f8ba.png)

**Comment by surfingtomchen** [comment]
me too

**Comment by ncreuschling** [comment]
We do not provide support for PlantUML itself.
